apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  labels:
    app:  {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  name: {{ template "name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Values.pv.storageSize }}
  hostPath:
    path: /data/pv0001/
  persistentVolumeReclaimPolicy: {{ .Values.pv.reclaimPolicy }}