apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
  name: {{ .Chart.Name }}
spec:
  serviceName:  {{ template "name" . }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app:  {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app:  {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: nats-streaming
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
         - "/bin/bash"
         - "-ec"
         - |
          CLUSTER_BOOTSTRAP=""
          echo $(hostname)
          if [[ "$(hostname)" =~ ^.*\-0$ ]]; then
            CLUSTER_BOOTSTRAP="-cluster_bootstrap"
          fi
          /opt/nats-streaming-server -m=8222 -st=FILE --dir=/nats-datastore -clustered ${CLUSTER_BOOTSTRAP} --cluster=nats://0.0.0.0:6222 --routes=nats://{{ template "name" . }}:6222 --cluster_log_path=/nats-cluster-log
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /nats-datastore2
          name: nats-datastore
          subPath: {{ .Values.volumeSubPath }}
        - mountPath: /nats-cluster-log2
          name: cluster-log-store
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: nats-datastore
        local:
          path: /mnt/disks/ssd1/storage2
      - name: cluster-log-store
        local:
          path: /mnt/disks/ssd1/logs2