image: nats-streaming:0.9.0-linux
imagePullPolicy: Always

replicas: 1

storageSize: 1Gi
# optional
volumeSubPath: nats-streaming

pv:
  serverUrl: 'FAKED'
  reclaimPolicy: Recycle
  storageSize: 2Gi
